apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-demo
  name: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              value: test
            - name: ENV_1
              valueFrom:
                secretKeyRef:
                  name: secrets-demo
                  key: ENV_1
            - name: ENV_2
              valueFrom:
                secretKeyRef:
                  name: secrets-demo
                  key: ENV_2
          image: 'kadashy/app-demo:latest'
          name: app-demo
          ports:
            - containerPort: 5000
              name: "http"
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: /probe/healthy
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              cpu: "100m"
              memory: "250Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-demo
type: Opaque
data:
  ENV_1: Rmlyc3RTZWNyZXQ=
  ENV_2: U2Vjb25kU2VjcmV0
  ENV_3: VGhpcmRTZWNyZXQ=
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "app-demo"
  labels:
    app: "app-demo"
spec:
  ports:
    - protocol: "TCP"
      port: 5000
  selector:
    app: "app-demo"
  type: "LoadBalancer"
