apiVersion: "v1"
kind: "Service"
metadata:
  name: "app-demo"
  namespace: "demo2"
  labels:
    app: "app-demo"
spec:
  ports:
    - protocol: "TCP"
      port: 5000
  selector:
    app: "app-demo"
  type: "LoadBalancer"
