apiVersion: "v1"
kind: "Service"
metadata:
  name: "app-demo"
  namespace: "demo"
  labels:
    app: "app-demo"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
  selector:
    app: "app-demo"
  type: "loadBalancer"
